version: '3.9'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db:/var/lib/postgres

    networks:
      - node-network
  app:
    depends_on:
      - postgresdb
    build: .
    env_file: .env
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    stdin_open: true
    tty: true
    networks:
      - node-network

volumes:
  db:
    driver: local

networks:
  node-network:
    driver: bridge
